- name: Set gnome clocks
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/clocks/world-clocks"
      value: "[{'location': <(uint32 2, <('Coordinated Universal Time (UTC)', '@UTC', false, @a(dd) [], @a(dd) [])>)>}]"

- name: Set gnome background/screensaver
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/gnome/amber-l.jxl'"
    - key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/gnome/amber-d.jxl'"
    - key: "/org/gnome/desktop/screensaver/picture-uri"
      value: "'file:///usr/share/backgrounds/gnome/amber-l.jxl'"

- name: Set gnome keybindings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
      value: "['<Super>w']"
    - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
      value: "['<Super>s']"
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
      value: "['<Shift><Super>w']"
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
      value: "['<Shift><Super>s']"

- name: Set gnome privacy
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/desktop/privacy/report-technical-problems"
      value: "false"

- name: Set gnome search providers
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/desktop/search-providers/disabled"
      value: "['org.gnome.Characters.desktop']"
    - key: "/org/gnome/desktop/search-providers/sort-order"
      value: "['org.gnome.Settings.desktop', 'org.gnome.Contacts.desktop', 'org.gnome.Nautilus.desktop']"

- name: Set gnome weather
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - key: "/org/gnome/Weather/locations"
      value: "[<(uint32 2, <('Canberra', 'YSCB', false, [(-0.6161012259539983, 2.6037403499491099)], @a(dd) [])>)>]"
